# Generated by Django 4.1.7 on 2023-03-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='prise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
